on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.5
        with:
          bundle: Iconic.flatpak
          manifest-path: build-aux/nl.emphisia.icon.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
