on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Create blank versions of configured file
        run: echo -e "" >> src/config.rs
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Add Flathub Beta remote
        run: |
          flatpak --user remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
          flatpak install --user -y flathub-beta org.freedesktop.Sdk.Extension.rust-stable//24.08beta org.freedesktop.Sdk.Extension.llvm18//24.08beta
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: iconic.flatpak
          # repository-name: flathub-beta
          manifest-path: build-aux/nl.emphisia.icon.Devel.json
          run-tests: false
          cache-key: flatpak-builder-${{ github.sha }}

  spell_check:
    name: Spell Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Python Dependencies
        run: pip install codespell
      - name: Run spellchecker
        run: codespell  -S po,_build,.git,.flatpak,_builddir,build,target -L crate,rouge,vermillion,trough

  update_translations:
    name: Update .pot template
    #this cannot be run on pull requests as it cannot commit
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install gettext
        run: |
          sudo apt update
          sudo apt install gettext -y
      - name: Update POTFILES.in
        run: |
          # remove old POTFILES.in
          rm po/POTFILES
          # add warning
          echo "# DO NOT EDIT MANUALLY" >> po/POTFILES
          echo "# This files is autogenerated a by script." >> po/POTFILES
          # add metadata files
          echo "# METADATA files" >> po/POTFILES
          echo "data/nl.emphisia.icon.desktop.in.in" >> po/POTFILES
          echo "data/nl.emphisia.icon.metainfo.xml.in.in" >> po/POTFILES
          # add ui files
          echo "# UI files" >> po/POTFILES
          find src -name "*.blp*" -print | sort >> po/POTFILES
          # add rust files
          echo "# RUST files" >> po/POTFILES
          grep gettext src/ -r | grep .rs  | cut -d: -f1 | uniq | sort >> po/POTFILES

      - name: Update Eyedropper.pot
        run: |
          ./scripts/make-pot.sh
          echo "POT_LINES_CHANGED=$(git diff -U0 | grep '^[+|-][^+|-]' | grep -Ev '^[+-]"POT-Creation-Date' | wc -l)" >> $GITHUB_ENV
      - name: Push changes
        if: ${{ env.POT_LINES_CHANGED != 0}}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore(translations): update template"
          add: "['po/folder_icon.pot', 'po/POTFILES.in']"
